CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  available boolean,
  user_id BIGINT,
  CONSTRAINT pk_item PRIMARY KEY (id),
  CONSTRAINT fk_item_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    owner_id BIGINT,
    renter_id BIGINT,
    item_id BIGINT,
    status VARCHAR(64),
    CONSTRAINT fk_booking_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_booking_renter FOREIGN KEY (renter_id) REFERENCES users (id),
    CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items (id)
);